### ISSUE TITLE
Reading out blood shards

### ISSUE THREAD

**Issue by DrBubble** [Enigma32/Enigma.D3#11]
Hi,

how can i read out the blood shards. Till now i was doing it with `PlayerData.Local.x88A4_VendorTokens[146].x04_Value`.
I also tried `PlayerData.Local.GetCurrency(CurrencyType.X1Shard);` but both return -1.

**Comment by d2k2-git** [comment]
with GetCurrency. But its not updated for Patch 2.6.0

public long GetCurrency(CurrencyType type)
{
const int size = 24; // { int index, int 0, long value, int 0, int 0 }
const int offset = 8;
return Read<long>(0x8D18 + size * (int)type + offset); //edit: 0x9D08 for Patch 2.6.0
}

**Comment by DrBubble** [comment]
The new offset worked thanks. How do you actually find out the new offset?

**Comment by d2k2-git** [comment]
i just made a simple loop which breaks when my gold amount is found. quick and dirty :D
