### ISSUE TITLE
Linking a skill to its icon texture

### ISSUE THREAD

**Issue by tehmufifnman** [Enigma32/Enigma.D3#12]
Anyone have an clue how this is done?  Trying to dig through and figure it out.  If not no biggie :) 

(feel free to label this a question, I wish I could do that before hand! silly github)

**Comment by Enigma32** [comment]
Inside the **2DUI_Skills_{Class}_All.tex** files, the name of a TexFrame matches the Power Slug with a suffix added based on state (_Inactive, _Mouseover, _Normal, _Pushed).

I don't know how to extract the actual textures, but I assume each TexFrame points to an area inside a large texture. That large texture data can be retrieved with:
```
var tex = SNOHelper.LoadFile<Textures>($"2DUI_Skills_{Class}_All.tex");
var data = tex.Read<byte>(
    tex.Content.x028_SerializeData[0].GetRelativeOffset(tex.Content),
    tex.Content.x028_SerializeData[0].Length);
```

It starts with 4x float values, then I guess the actual image data comes.

**Comment by tehmufifnman** [comment]
Thanks for that!  Still having a bit of trouble.  I tried skipping the 4x floats and writing the bytes to a file but its gibberish (to an image editor) still.

I decided to take a step back and just work with the raw bytes before moving on to Enigma stuff, just to see if I could get a better understanding.  I got so far as getting the "whole" images width and height - maybe this can help clarify things in Enigma?  If you have any more insight that would be awesome.

`            var data = File.ReadAllBytes(Path.Combine(_basePath, "Textures", texFile));
            var ms = new MemoryStream(data);
            var reader = new BinaryReader(ms);

            var head = reader.ReadInt32();
            var type = reader.ReadInt32();
            reader.ReadInt32();
            reader.ReadInt32();

            reader.ReadInt64();
            reader.ReadInt64();

            var compType = reader.ReadInt32();
            var width = reader.ReadInt32();
            var height = reader.ReadInt32();
            var imageCount = reader.ReadInt32();`
