### ISSUE TITLE
Request: Enigma.D3.MemoryModel.Core.ACD.AnimTag // isTeleporting

### ISSUE THREAD

**Issue by d2k2-git** [Enigma32/Enigma.D3#16]
Need a way to find out if the player is teleporting by using the new MemoryModel

D3.Memory had a GetAnimTag function:
https://github.com/Enigma32/Enigma.D3/blob/ac3ac7d39546ed9aae2ba875af3f564328362f53/Enigma.D3.Memory/D3/ActorCommonData.cs#L209

bool isTeleporting = (AnimTag== 0x68500) || (AnimTag== 410129);

**Comment by Enigma32** [comment]
Implemented with https://github.com/Enigma32/Enigma.D3/commit/c9dd7bfbfcc0d510e9577abe8ed87a09b06afa07

You get to do the null checking yourself :)
