### ISSUE TITLE
Request : Get selected ACD or ActorID with MemoryModel

### ISSUE THREAD

**Issue by d2k2-git** [Enigma32/Enigma.D3#18]
I need a way to get the selected ActorID or the ACD with MemoryModel

see function in d3helper project:
https://github.com/d2k2-git/D3Helper.Public/blob/MemoryModel/D3Helper/A_Tools/T_LocalPlayer.cs#L169-L215

```
var selectedActorID = Engine.Current.ObjectManager.xA30_PlayerInput.Dereference().x00_ListB_Of_ActorId.ToList()[0];

var selectedType = Engine.Current.ObjectManager.xA30_PlayerInput.Dereference().x14_StructStart_Min56Bytes
```

I am not sure forwhat  is selectedType used for. i guess if selectedType == 44580 then it is an attackable ACD ?

**Comment by Enigma32** [comment]
44580 appears to be a Texture SNO: "cursor_attack_normal"

**Comment by Enigma32** [comment]
https://github.com/Enigma32/Enigma.D3/commit/c04cdef491d5d535bf0b73c4d3eac2302c0cc04a adds TargetACDID in UIManager. This should be easier to use. When a monster health bar is shown, it's for this ACDID. -1 = none.
