### ISSUE TITLE
Update Enigma.D3.Enums.HeroClass

### ISSUE THREAD

**Issue by d2k2-git** [Enigma32/Enigma.D3#19]
I guess Necromancer = 6
https://github.com/Enigma32/Enigma.D3/blob/master/Enigma.D3.Core/Enums/HeroClass.cs

**Comment by Enigma32** [comment]
Correct. Added with https://github.com/Enigma32/Enigma.D3/commit/569e6e10104e397f499a79cef6a9abfe6b38804f
