### ISSUE TITLE
offsets 2.4.3 - CodeGenerator crashing

### ISSUE THREAD

**Issue by d2k2-git** [Enigma32/Enigma.D3#2]
Can you update the offsets for 2.4.3?
The CodeGenerator is crashing when i try to read the dump

codegenerator crashing here:
`methodPtrs.Add("SNOGroups_Initialize", TranslateToVA(symbols.BestMatch("CSnoGroups::Initialize")));`

**Comment by Enigma32** [comment]
Working on it.

**Comment by Enigma32** [comment]
Done
