### ISSUE TITLE
How do you get proper details for Script Formulas?

### ISSUE THREAD

**Issue by tehmufifnman** [Enigma32/Enigma.D3#23]
Diablo Build: 46568

For example the description string from `Powers.stl` for the Necromancer spell Siphon Blood once processed through Enigma reads

```
{c_gold}Generate:{/c} {c_green}{Script Formula 29}{/c} Essence each time damage is dealt
Siphon the blood from the targeted enemy dealing {c_green}[{Script Formula 0}*200]%{/c_green} weapon damage as Physical.
Siphon Blood heals you for {c_green}[{Script Formula 30}*100]%{/c_green} of your total health every second while channeled.
```

If I read the corresponding `P6_Necro_SiphonBlood.pow` and look in the `ScriptFormulaDetails` array I see

![awiovoc 1](https://user-images.githubusercontent.com/436828/28535690-e412e1ea-706a-11e7-841a-fc198aaa29db.png)

![o8wpvvv 1](https://user-images.githubusercontent.com/436828/28535619-a9a083aa-706a-11e7-882e-5362439e2016.png)

![kwuhwya 1](https://user-images.githubusercontent.com/436828/28535757-2092a240-706b-11e7-8687-0a1e414e8268.png)

The actual spell via Blizzard's website read

```
Generate: 15 Essence each time damage is dealt
Siphon the blood from the targeted enemy dealing 300% weapon damage as Physical.
Siphon Blood heals you for 2% of your total health every second while channeled.
```

I am not seeing any way to properly map the Script Formulas to their true values.  I appreciate any insight, keep up the amazing work!

P.S. Anywhere we can buy you a beer?

**Comment by Enigma32** [comment]
Maybe it's in the PowerFormula GameBalance. Otherwises I don't know.

P.S. There's a donation link in README.md

**Comment by tehmufifnman** [comment]
So I did some more digging into this, and maybe your expertise can help a little more.  I will keep digging though.

If you look at the raw content of (for this example) `P6_Necro_SiphonBlood.pow` you will see this

https://pastebin.com/ym8XbJ4V

Now you can see in there several tags similar to 

`PowerTag.P6_Necro_Passive_BuilderAttackSpeed."Script Formula 0"`
or
`SF_29 * 1.3`

I don't see this information represented anywhere in the SNOFile<Power> object.  In addition, the PowerTag obviously maps to a secondary *.pow file, and the SF_XX somehow maps to a value that math needs to be run on.

I will keep digging!

**Comment by Enigma32** [comment]
I can see that data is inside Content.x050_PowerDef.x018_TagMap.
These tag maps have always been a mystery to me.

**Comment by Enigma32** [comment]
Type TagMap has now been added. Turns out it's a dictionary containing mixed value types.

**Comment by tehmufifnman** [comment]
Great work!  The TagMaps are working perfectly.
