### ISSUE TITLE
Parse TAG_POWER Entries

### ISSUE THREAD

**Issue by tehmufifnman** [Enigma32/Enigma.D3#24]
Not sure if this is possible, but it would be nice if `TAG_POWER_[NAME]` could be parsed from the `Diablo III.exe` and then their values made available as part of the code generation process.

You can see at one point Mooege parsed them all out here, however new values have obviously been added and existing values have changed.
https://github.com/vrobel/mooege/blob/master/src/Mooege/Core/GS/Common/Types/TagMap/PowerKeys.cs

**Comment by Enigma32** [comment]
I've added TagDescriptor. You can get them all using
```
var address = SymbolTable.Current.Platform == Platform.X86 ? 0x2147CCC : 0x141E60F40;
var maps = ctx.Memory.Reader.Read<Ptr<Map<int, Ptr<TagDescriptor>>>>(address).ToArray(19);
```
Not all have names/descriptions.
