### ISSUE TITLE
Getting started guide?

### ISSUE THREAD

**Issue by jchristn** [Enigma32/Enigma.D3#25]
Hi there, sorry for the noob question, couldn't find documentation in the code or in the repo that would point to a simple getting started process, i.e. spawning D3 and then initializing the class library to attach to the process.  Any such document exist?  Thanks!

**Comment by d2k2-git** [comment]
You can check for example the MapHack project
https://github.com/Enigma32/Enigma.D3/tree/master/Enigma.D3.MapHack


Basicly you start with:
`var ctx = MemoryContext.FromProcess();`

and after you either use the ApplicationSnapshot (This is the high level API)
`var snapshot = new ApplicationSnapshot (ctx);`


or you directly access the Memory over the MemoryContext (This is the low level API)
```
ctx.DataSegment...
or
MemoryContext.Current.DataSegment...

```

**Comment by jchristn** [comment]
Thanks, I'm looking here (https://github.com/Enigma32/Enigma.D3/blob/master/Enigma.D3.MapHack/D3/Bootloader/App.cs) and don't see where the process ID is defined - or is this something the library itself figures out on its own?  Again sorry for the noob questions...

**Comment by d2k2-git** [comment]
MemoryContext.FromProcess() is doing the job for you. it access the memory by processname.

**Comment by Enigma32** [comment]
Load the solution/project and follow the definitions/references :) Then you'd end up in https://github.com/Enigma32/Enigma.D3/blob/master/Enigma.D3.MemoryModel/MemoryContext.cs and see that there is a method that accepts a Process instance. So if you want it for a specific PID, first find the matching process and then create a MemoryContext for it.

**Comment by jchristn** [comment]
Thank you - closing this for now and will open new issue(s) if/when encountered!  Thanks!
