### ISSUE TITLE
Is this table static?

### ISSUE THREAD

**Issue by treenewbee** [Enigma32/Enigma.D3#28]
https://github.com/Enigma32/Enigma.D3/blob/59be056195e93b929beb74a23b7c05e3856bdfc2/Enigma.D3.MemoryModel/SymbolTable.X86.cs#L26

Yesterday this table seems to be true, but today the MapActID seems to be 202D5400 or "Diablo III.exe"+18D5440

Also ApplicationLoopCount = 0x205C16C, now it is 020D566C in my cheat engine. Do I need to get a base address plus offset/follow a pointer or something?

**Comment by Enigma32** [comment]
For this version (https://github.com/Enigma32/Enigma.D3/blob/59be056195e93b929beb74a23b7c05e3856bdfc2/Enigma.D3.MemoryModel/SymbolTable.X86.cs#L13) yes, but what you linked is in the legacy branch. Use the master branch if that's not what you're already doing.

**Comment by treenewbee** [comment]
Right, no idea how I ended up in the legacy branch, and 0x205C16C seems to be some other counter.
