### ISSUE TITLE
Codegen 2.4.3.43048

### ISSUE THREAD

**Issue by d2k2-git** [Enigma32/Enigma.D3#3]
Hi Enigma,
the codegen is crashing reading the latest d3 memory
at
Enigma.D3.CodeGen.Memory.Generator.GetOffset_PlayerData_HeroName(UInt32 sizeof_playerdata)

**Comment by Enigma32** [comment]
Alright. Working on it.

**Comment by Enigma32** [comment]
Fixed with https://github.com/Enigma32/Enigma.D3/commit/3593e32ff68c9acc643bd91ef1a26040d2053cbd
