### ISSUE TITLE
[ApplicationModel] Item.ItemName always null

### ISSUE THREAD

**Issue by Xqzmeplz** [Enigma32/Enigma.D3#31]
Hello,

the ItemName property from the Item class always returns null.

I was able to observe the following behavior, explained with this example item:
Name: Band of Hollow Whispers
x000_Text: Unique_Ring_001
x108_ActorSno (aka slug?): Ring_norm_unique_001
(data from http://d3planner.com/game/raw/)

The Item passes his slug "Ring_norm_unique_001" to the AssetCache.GetItemName Method.
The AssetCache tries to lookup the slug inside the _itemsStringLookup dictionary,
this fails because the key of the _itemsStringLookup dictionary is "Unique_Ring_001".
The dictionary is build with the x000_Text and the item name.

Originally i was trying to get the x000_Text for the item. Is there a good way to access this value?

Regards,
Xqzmeplz

**Comment by ZenDraL** [comment]
Did you ever figure out how to get the x000_Text Xqzme?

**Comment by Xqzmeplz** [comment]
@ZenDraL Regarding to your question. I couldn't figure out a way to access the x000_text.

**Comment by ZenDraL** [comment]
I put the following together from some of the posts on the forum. There's other properties worth looking at as well but I left them out to keep the post small. If you're only after the name you could consider getting rid of the ItemProperties struct and just using a string instead.

```csharp
    // Added this to AssetCache
    public struct ItemProperties {
        public string ItemName { get; set; }
    }

    private static Dictionary < GBID, ItemProperties > _itemsMap = new Dictionary < GBID, ItemProperties > ();
    
    HashSet <int> Allowed = new HashSet <int> () { 19750, 19753, 19754, 170627 };
    ctx.DataSegment.SNOGroupStorage[(int) SNOType.GameBalance]
     .Cast <SNOGroupStorage<GameBalance>> ()
     .Dereference()
     .Container
     .Where(x => x.SNOType == SNOType.GameBalance)
     .Where(x => x.ID != -1)
     .Select(x => x.PtrValue.Dereference())
     .Where(x => x != null && Allowed.Contains(x.x000_Header.x00_SnoId))
     .Select(x => x.x028_Items.x08_Items)
     .ForEach(x => {
      foreach(var item in x) {
       if (!_itemsMap.ContainsKey((uint) item.x100)) {
        _itemsMap[(uint) item.x100] = new ItemProperties { 
          ItemName = GetItemName(item.x000_Text),
        };
       }
      }
     });

    // Then you can get the name like this. 
    item.Name = AssetCache.GetItemProperties(item.ACD.GBID).ItemName;
```
