### ISSUE TITLE
Player movement

### ISSUE THREAD

**Issue by ZenDraL** [Enigma32/Enigma.D3#33]
I found this on the forum. Which I assume is from the legacy version. Could you please tell me if there is a way to do this with the new version? Just the boolean would be enough for me. Thanks.

> >Enigma, i created a way to see if the hero is moving or not but do you have a way already within the framework?

>  Just a boolean? Actor.x3DC != 0 => IsMoving
> there are plenty of ways, there is also the ActorMovement struct related to Actor with lots of goodies.

**Comment by d2k2-git** [comment]
i found this on local PlayerData Object


 public class PlayerData : MemoryObject
{
     public bool IsMoving => this.Read<bool>(0xC528); //64 bit offset 
      ...

**Comment by ZenDraL** [comment]
That's pretty neat but then what if they're holding forced standstill or using force move instead of left click. I can do some sort of check to see if the position is changing over time I guess. But if there's a boolean on the ACD or something like that I think it would be better.

**Comment by d2k2-git** [comment]
would prefer a boolean too. right now i am just comparing if the position has changed in last 500ms

**Comment by ZenDraL** [comment]
Fair enough, I've been looking at seeing if you can tell from the animation tag but that seems like it might be a pain in the ass.

**Comment by d2k2-git** [comment]
i dont know if the animation tag is different for each class. i guess so. 

however i could not find anything except vectors chagning in the ACD or Playerdata  while player is moving.

**Comment by d2k2-git** [comment]
there is also an ActorMovement struct. but its not implemented in the MemoryModel

https://github.com/onethawt/enigma-d3/blob/4f72539832fd36e3e2ac4beb69ad1c6a80d7940c/Enigma.D3.Memory/D3/Actor.cs#L92

**Comment by ZenDraL** [comment]
I did some poking around the player's Actor in memory and I'll be honest I'm not sure what I'm reading. If I had to guess it would be the player's acceleration since it doesn't hit zero until the player comes to a complete stop. 
```csharp
public bool IsMoving => playerActor.Read<uint>(SymbolTable.Current.Platform == Platform.X64 ? 0x47C : 0x3E4) > 0;
```
Enigma if you have more insight or could support this functionality sometime in the future that would be great. If not feel free to close this ticket.

**Comment by d2k2-git** [comment]
@ZenDraL 
i can not find anything at ACD.0x47C. its always 0 for the local ACD

**Comment by ZenDraL** [comment]
It's not on the ACD it's on the Actor object.

**Comment by d2k2-git** [comment]
tested. working. just implement it correctly (offsets into symboltables x86 and x64) and make pullrequest :> maybe Enigma will merge it for us.

i just hope the Actor structure does not change so often

**Comment by d2k2-git** [comment]
There is also another Movement flag (0 or 1) in the Actor inside a structure

//x64
```
        public static bool isActorMoving(this Enigma.D3.MemoryModel.Core.Actor actor)
        {
            var movementStruct = actor.ReadPointer<MemoryObject>(0x1D0).Dereference();
            bool IsMoving = movementStruct.Read<int>(0x38) > 0; // 0=not moving , 1=moving
            return IsMoving;
        }
```

**Comment by d2k2-git** [comment]
doesnt work anymore :S

**Comment by brusej** [comment]
I always appreciate your efforts. 
-----Original Message-----
