### ISSUE TITLE
ApplicationModel crashes on initializing AssetCache and HotkeyPreferences

### ISSUE THREAD

**Issue by zachking** [Enigma32/Enigma.D3#38]
There are two issues currently in the ApplicationModel framework. I believe some addresses/offsets may be incorrect. I'm fairly new to reading memory structures, otherwise, I would have spent more time trying to debug it.

**`ApplicationSnapshot.cs`**
```
public void Update()
{
    ...
        if (!AssetCache.IsInitialized)
            AssetCache.Initialize(MemoryContext); // Win32.ReadProcessMemory() Error
    ...
        (_hotkeyCache = _hotkeyCache ??MemoryContext.DataSegment.HotkeyPreferences).TakeSnapshot(); // Win32.ReadProcessMemory() Error
    ...
}
```

The full Exception value is:
> **System.ComponentModel.Win32Exception: 'Only part of a ReadProcessMemory or WriteProcessMemory request was completed'**

I'm fairly proficient in C# and coding in general, so please ask for more information if this is not enough. Your work on Enigma.D3 is much appreciated. I am enjoying building off your framework. It is very clean.

**Comment by zachking** [comment]
I am using your `post-obfuscation-patchwork` branch.

**Comment by d2k2-git** [comment]
SymbolTable.x64.cs is not updated completly for current patch

DataSegment.HotkeyPreferences = 0x1EF8730;     //new
DataSegment.SNOFiles = 0x2168690;                   //new
ataSegment.ApplicationLoopCount = 0x216C2A4;           //new

aswell DataSegment.cs
 public SNOFiles SNOFiles
            => Memory.Reader.Read<Ptr<SNOFiles>>(MemoryContext.Current.ImageBase + SymbolTable.Current.DataSegment.SNOFiles).Dereference();

   public HotkeyPreferences HotkeyPreferences
            => Memory.Reader.Read<HotkeyPreferences>(MemoryContext.Current.ImageBase + SymbolTable.Current.DataSegment.HotkeyPreferences);

  public int ApplicationLoopCount
            => Memory.Reader.Read<int>(MemoryContext.Current.ImageBase + SymbolTable.Current.DataSegment.ApplicationLoopCount);

**Comment by Enigma32** [comment]
I didn't think ApplicationModel was actually used by anyone :D Now that I look at it, it's pretty cool. Should probably try to integrate with MapHack better.

Offsets updated with
https://github.com/Enigma32/Enigma.D3/commit/06a97d00ffc26bd7ead64db28c9ffef8f89c071f

Will look at getting all offsets updated, but should be enough for ApplicationModel now.
