### ISSUE TITLE
OSX Port

### ISSUE THREAD

**Issue by logikaljay** [Enigma32/Enigma.D3#39]
Heya,

Used this library for a little bit on Windows - really love the work you have done.

I have the project compiling with mono on OSX with some minor modifications.

Where I am stuck is when it comes time to actually reading from memory.

Obviously kernel32.dll isn’t available on OSX so there is no ReadProcessMemory.
However we do have vm_read which according to the Apple docs allows a privileged user to read another processes memory.

My question is: Do you think it is possible to port this to OSX or am I wasting my time?

**Comment by Enigma32** [comment]
Hi,

I would expect the executable for OSX to have different memory addresses, possibly offsets as well. OSX also uses a different file format (no .exe) which I have no experience of with, how it loads, or what it contains. So trying to port without knowing how to reverse engineer on OSX would be a waste of time in my opinion.
