### ISSUE TITLE
Reading rift progress

### ISSUE THREAD

**Issue by Cr33zz** [Enigma32/Enigma.D3#41]
I tried to find X790 structure pointer location in ObjectManager and then RiftProgress. I've spend like an hour figuring this stuff but I failed. I have used following code:

```
for (int i = 0x650; i < 0x950; i += 4)
{
    try
    {
        int flags = MemoryContext.Current.DataSegment.ObjectManager.Read<Ptr<ObjectManager.X790>>(i).Dereference().Read<int>(0);

        if ((flags & 0x0010) != 0)
            Trace.WriteLine("0x" + i.ToString("X8"));
        else
            continue;

        for (int j = 0x000; j < 0x124; j += 4)
        {
            double pct = Math.Round(MemoryContext.Current.DataSegment.ObjectManager.Read<Ptr<ObjectManager.X790>>(i).Dereference().Read<float>(j) / 6.5, 3);

            if (pct > 0 && pct < 150)
                Trace.WriteLine("0x" + i.ToString("X8") + "   " + "0x" + j.ToString("X8") + "   " + pct + "%");
        }
    }
    catch (Exception) {}
}
```

I wanted to leverage the fact that at offset 0 in X790 struct there were flags and 0x10 was supposed to be InGame according to legacy Enigma code. Then I expected that number of souls didn't change dramatically. I was running the same code a few times, every time after killing some monsters inside rift expecting to see some steadily increasing numbers but it's all garbage.

**Comment by d2k2-git** [comment]
you can read the riftprogress from the ui controls:

"Root.NormalLayer.eventtext_bkgrnd.eventtext_region.stackpanel.rift_wrapper.greater_rift_container.rift_progress_bar"

or

"Root.NormalLayer.eventtext_bkgrnd.eventtext_region.stackpanel.rift_wrapper.rift_container.rift_progress_bar"

```
public class ProgressControl : Control
{
    public float RiftProgress => this.Read<float>(0xA58); //64bit only
}
```

**Comment by Enigma32** [comment]
The pointer from ObjectManager is encrypted so we'd either need to find the decrypt key(s) or add a signature scan in SymbolPatcher.

**Comment by Cr33zz** [comment]
Thanks guys. I forgot about that :/ I can read it from UI then. I would be more beneficial to find BuffManager pointer through signature can IMO (I'll create separate issue for it).
