### ISSUE TITLE
BuffManager address

### ISSUE THREAD

**Issue by Cr33zz** [Enigma32/Enigma.D3#42]
BuffManager contains some information about buff that I don't think can be easily accessed otherwise (perhaps except for trying reading it from UI). I tried to get Raekor's Charge stacks count (having 100 of them) from player attributes but there are 3 entries for it's power sno id modifier BuffIconCount1 (value 100), BuffIconCount0 (value 1) and BuffIconCount2 (value 0). It's hard to tell which value stores actual stacks by just going over all buff icons for any given power sno id in general case. Second thing is Convention of Elements buff. It's changing elemental type and current one was stored in Buff structure at x004_Neg1. If that is possible it would be great to have access to BuffManager again :)

**Comment by Enigma32** [comment]
5aa7f02e9def8f855e9c8a1bbe8a6da91f46d62a

**Comment by Cr33zz** [comment]
You are godsend!
