### ISSUE TITLE
GameTick always 0

### ISSUE THREAD

**Issue by d2k2-git** [Enigma32/Enigma.D3#5]
HI Enigma,

i was trying to update my project with your latest commit. GameTick always return 0.
Can you check it?

 Engine.Current.ObjectManager.x7B0_Storage.x118_GameTick;

Probably more stuff must be fixed. i will check tomorrow. Thx for your work :)

**Comment by Enigma32** [comment]
Fixed with 02e15e33920abf1f1c70f519f2524eb2586fb774
