### ISSUE TITLE
PrimaryGesture.Key always ESCAPE

### ISSUE THREAD

**Issue by d2k2-git** [Enigma32/Enigma.D3#6]
Seems 

Hotkey.Get(HotkeyIndex.ActionBarSkill2).PrimaryGesture.Key;

always returns "ESCAPE" as Hotkey in the current version.

**Comment by d2k2-git** [comment]
correct for current diablo version.
public const int HotkeyPreferences = 0x01E0F528;

https://github.com/Enigma32/Enigma.D3/blob/master/Enigma.D3.Memory.Generated/ObjectPtr.cs#L7

**Comment by Enigma32** [comment]
The property **KeybindingVersion** is at 0x01E0F524. The actual hotkeys are after it, +4, which matches the address you got it to. I'll make sure to update the codegen as well.
