### ISSUE TITLE
ActorCommonData.Container NULL in 2.6.0

### ISSUE THREAD

**Issue by d2k2-git** [Enigma32/Enigma.D3#7]
I see you work on the 2.6.0 Update already. I did a quick test with d3helper with latest commits.

ActorCommonData.Container returns NULL

https://github.com/Enigma32/Enigma.D3/blob/master/Enigma.D3.Memory/D3/ActorCommonData.cs#L199

I hope its ok to report this kind of bug so early. Keep up the good work :>

**Comment by Enigma32** [comment]
See updated offsets at https://github.com/Enigma32/Enigma.D3/blob/master/Enigma.D3.MemoryModel/SymbolTable.X86.cs

I'll update Enigma.D3.Memory tomorrow. Be aware that Enigma.D3.Memory is going obsolete and will be replaced by Enigma.D3.MemoryModel. I'll write a post on OC.

**Comment by Enigma32** [comment]
Should be solved with dd28e00e19b26e451bed63a4e3551f801fd82ab2
Please confirm and close issue.

**Comment by d2k2-git** [comment]
ActorCommonData.Container  does not return anymore NULL. but there seems to be more issues i have:


For Example:
GetActiveSkills returns array where PowerSno is 0 everywhere

		public ActiveSkillSavedData[] GetActiveSkills()
		{
			return x00A0_ServerData.x000C_PlayerSavedData.x1218_ActiveSkillSavedData;
		}
