### ISSUE TITLE
GetActiveSkills()  returns array with "0" Values

### ISSUE THREAD

**Issue by d2k2-git** [Enigma32/Enigma.D3#8]
GetActiveSkills returns array where PowerSno and RundeId is 0 everywhere

		public ActiveSkillSavedData[] GetActiveSkills()
		{
			return x00A0_ServerData.x000C_PlayerSavedData.x1218_ActiveSkillSavedData;
		}

I am aware that D3.Memory will be obsolete soon. If you will not update D3.Memory anyonemore, is there another way to get the "PowerSnoId" and "RuneId" of the active skills?

**Comment by Enigma32** [comment]
Should be fixed with 6b8aeb4d18bbd4680c506b8feb5c259f73ceea52

With MemoryModel, it can be retrieved as such (simplified API will come)
```
var ctx = new MemoryContext(new ProcessMemoryReader(
    Process.GetProcessesByName("Diablo III").FirstOrDefault() ??
    Process.GetProcessesByName("Diablo III64").FirstOrDefault())
    ?.Memory);

var playerData = ctx.DataSegment.ObjectManager.PlayerDataManager[ctx.DataSegment.ObjectManager.Player.LocalPlayerIndex];
var activeSkills = playerData.PlayerSavedData.ActiveSkillSavedData;
var passiveSkills = playerData.PlayerSavedData.PassiveSkills;
```
