### ISSUE TITLE
Reading out the rift progress

### ISSUE THREAD

**Issue by DrBubble** [Enigma32/Enigma.D3#9]
Hi,
till now i was reading out the rift progress with
`Math.Round(ObjectManager.Instance.x7A8_Ptr_292Bytes.Dereference().x0F4_RiftProgress / 6.5, 2);`
x7A8_Ptr_292Bytes does not exist anymore with the newest version. Is there an other way to read out the rift progress?

**Comment by Enigma32** [comment]
You can try uncommenting https://github.com/Enigma32/Enigma.D3/blob/dd28e00e19b26e451bed63a4e3551f801fd82ab2/Enigma.D3.Memory/D3/ObjectManager.cs#L37 and update the offset used for read to 0x7D8. I'm not sure that offset will work, so if it does not then you can try a few steps of +-4 and see if you hit the spot.

**Comment by DrBubble** [comment]
0x7D8 worked, thanks.
